{% if environ.get('TRAVIS', False) %}
  {% set version = environ.get('TRAVIS_BRANCH', '0.0') %}
  {% set build_num = environ['TRAVIS_BUILD_NUMBER'] %}
{% elif environ.get('APPVEYOR', False) %}
  {% set version = environ.get('APPVEYOR_REPO_TAG_NAME', '0.0') %}
  {% set build_num = environ['APPVEYOR_BUILD_NUMBER'] %}
{% else %}
  {% set version = environ.get('GIT_DESCRIBE_TAG', '0.0') %}
  {% set build_num = environ.get('GIT_DESCRIBE_NUMBER', 0) %}
{% endif %}
{% set version = version.replace('v','').replace('untagged', '0.0').split('-')[0] %}

package:
  name: pydrobert-speech
  version: {{ version }}

source:
  path: ..

requirements:
  build:
    - setuptools
    - setuptools_scm
  run:
    - python >=3.6
    - numpy
  run_constrained:
    - pydrobert-param >0.2.0
    - pydrobert-kaldi >0.5.3
    - pydrobert-pytorch >0.2.1

build:
  noarch: python
  number: {{ build_num }}
  skip: True  # [py < 36]
  entry_points:
    - compute-feats-from-kaldi-tables = pydrobert.speech.command_line:compute_feats_from_kaldi_tables
    - signals-to-torch-feat-dir = pydrobert.speech.command_line:signals_to_torch_feat_dir
  script:
    - export SETUPTOOLS_SCM_PRETEND_VERSION=${PKG_VERSION}  # [not win]
    - set SETUPTOOLS_SCM_PRETEND_VERSION=%PKG_VERSION%  # [win]
    - python setup.py install --single-version-externally-managed --record=record.txt

test:
  source_files:
    - tests
  requires:
    - pytest
    - scipy
    - h5py
    # pytorch for 3.9 currently needs conda-forge
    - pytorch  # [py < 39]
    - pydrobert-kaldi
  imports:
    - pydrobert
    - pydrobert.speech
  commands:
    - compute-feats-from-kaldi-tables -h
    - signals-to-torch-feat-dir -h  # [py < 39]
    - pytest

about:
  home: https://github.com/sdrobert/pydrobert-speech
  license: Apache License 2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Speech processing with Python
