version: build.{build}.branch.{branch}
image: Visual Studio 2019

environment:
  matrix:
    - TOXENV: py37
    - TOXENV: py38
    - TOXENV: py39
    - TOXENV: py310
    - job_name: dist

branches:
  except:
    - /docs/

stack: python 3.7

for:
  -
    matrix:
      only:
        - TOXENV: "py38"
        - TOXENV: "py39"
    skip_non_tags: true
  
  -
    matrix:
      only:
        - job_name: dist
    skip_non_tags: true
    install:
      - python -m pip install -U pip build twine wheel
    build: script
    build_script:
      - python -m build -o dist
    test_script:
      - ps: python -m twine check (Resolve-Path 'dist\*').Path
      - ps: python -m pip install (Resolve-Path 'dist\*.whl').Path pytest
      - python -m pytest
    artifacts:
      path: 'dist\*'

build: off

install:
  - python -m pip install -U pip wheel setuptools
  - python -m pip install -U tox

test_script:
  - python -m tox
