version: build.{build}.branch.{branch}

environment:
  matrix:
    # - TOXENV: py37
    # - TOXENV: py38
    # - TOXENV: py39
    # - TOXENV: py310
    - job_name: dist

branches:
  except:
    - /docs/

for:
  - 
    matrix:
      except:
        - job_name: dist
    image: Visual Studio 2019

  -
    matrix:
      only:
        - TOXENV: "py38"
        - TOXENV: "py39"
    skip_non_tags: true
  
  -
    matrix:
      only:
        - job_name: dist
    image: Ubuntu
    stack: python 3.7
    install:
      - python -m pip install build twine wheel
    build: script
    build_script:
      - python -m build -o dist
    test_script:
      - python -m twine check dist/*
      - python -m pip install dist/*.whl pytest
      - python -m pytest
    artifacts:
      path: 'dist\*'

build: off

install:
  - py -3.7 -m pip install -U pip wheel setuptools
  - py -3.7 -m pip install -U tox

test_script:
  - py -3.7 -m tox
