# dev environment
name: pydrobert-speech
channels:
  - pytorch
  - conda-forge
  - nodefaults
dependencies:
  - cpuonly
  - h5py
  - ipython
  - matplotlib
  - numpy
  - pydrobert-kaldi
  - pysoundfile
  - pytest
  - pytorch
  - scipy
  - webdataset
